--for Mysql DBMS
CREATE DATABASE ReactiveSnail;

USE ReactiveSnail;

CREATE TABLE DRIVER(
    ID INT PRIMARY KEY AUTO_INCREMENT 	NOT NULL,
    LASTNAME   			VARCHAR(255) 	NOT NULL,
    FIRSTNAME			VARCHAR(255) 	NOT NULL,
    PATRONYMIC 			VARCHAR(255),
    YEAR_OF_BIRTH 		DATE			NOT NULL,
    DATE_OF_EMPLOYMENT 	DATE			NOT NULL,
    DRIVING_EXPERIENCE	DATE			NOT NULL,
    PHOTO 				VARCHAR(255)    DEFAULT '/photo/ava_default.png'
	);
