--for Mysql DBMS
CREATE DATABASE ReactiveSnail;

USE ReactiveSnail;

CREATE TABLE DRIVER(
    ID INT PRIMARY KEY AUTO_INCREMENT 		NOT NULL,
    LASTNAME   				VARCHAR(255) 	NOT NULL,
    FIRSTNAME				VARCHAR(255) 	NOT NULL,
    PATRONYMIC 				VARCHAR(255),
    YEAR_OF_BIRTH 			DATE			NOT NULL,
    DATE_OF_EMPLOYMENT 		DATE			NOT NULL,
    DRIVING_EXPERIENCE		DATE			NOT NULL,
    PHOTO 					VARCHAR(255)    DEFAULT '/photo/ava_default.png'
    );

INSERT INTO DRIVER (LASTNAME, FIRSTNAME, PATRONYMIC, YEAR_OF_BIRTH, DATE_OF_EMPLOYMENT, DRIVING_EXPERIENCE, PHOTO)
VALUES ("Ivanov", "Ivan", "Ivanovich", '1995.03.03', '2016.03.03', '2015.03.09', "/photo/IvanII.png");
